version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
       - ./wordpress.sql:/docker-entrypoint-initdb.d/init.sql
     restart: always
     ports:
      - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   adminer:
     image: adminer
     restart: always
     ports:
       - 8080:8080

   mailhog:
     image: mailhog/mailhog
     ports:
       - 1025:1025 # smtp server
       - 8025:8025 # web ui

   wordpress:
     depends_on:
       - db
     build: ./container/wordpress
     hostname: wordpress
     ports:
       - 8000:80
     restart: always
     working_dir: /var/www/html
     volumes:
      - ./:/var/www/html/wp-content
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_TABLE_PREFIX: wp_
       WORDPRESS_DEBUG: 1
       WORDPRESS_CONFIG_EXTRA: |
          define('WP_ENV', 'development');
          define('WP_CACHE', false);
          define('WP_SITEURL', 'http://' . $$_SERVER['HTTP_HOST'] . '/');
          define('WP_HOME', 'http://' . $$_SERVER['HTTP_HOST'] . '/');
          define('GRAPHQL_DEBUG', true);
volumes:
    db_data: {}
